<a href="https://colab.research.google.com/github/habib-153/AI-ML/blob/Deep-learning/backprop_using_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

# Tensor Shape

In [ ]:
x = torch.tensor([[1,2,3], [4,5,6]])
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3544956554084312633]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.3130, 0.8942, 0.8692],
        [0.0069, 0.6818, 0.8298]])

In [ ]:
torch.tensor([1.0, 2.0, 3.0, 4.0], dtype=torch.int32)

tensor([1, 2, 3, 4], dtype=torch.int32)

# Mathmatical Operation

In [ ]:
x+2

tensor([[3, 4, 5],
        [6, 7, 8]])

In [ ]:
x-2

tensor([[-1,  0,  1],
        [ 2,  3,  4]])

In [ ]:
x/2

tensor([[0.5000, 1.0000, 1.5000],
        [2.0000, 2.5000, 3.0000]])

In [ ]:
x * 10

tensor([[10, 20, 30],
        [40, 50, 60]])

In [ ]:
x // 3

tensor([[0, 0, 1],
        [1, 1, 2]])

# Element wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

a+b
a-b

tensor([[ 0.0599,  0.8625,  0.5335],
        [ 0.1045, -0.3658, -0.0271]])

In [ ]:
a%b

tensor([[0.0599, 0.0191, 0.1353],
        [0.1045, 0.0853, 0.3593]])

In [ ]:
a**b

tensor([[0.8388, 0.9967, 0.9722],
        [0.8768, 0.3294, 0.6734]])

In [ ]:
c = torch.tensor([-1, -2, -3, -4])

In [ ]:
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
torch.neg(a)

tensor([[-0.7846, -0.8915, -0.9318],
        [-0.8353, -0.0853, -0.3593]])

In [ ]:
torch.round(a)

tensor([[1., 1., 1.],
        [1., 0., 0.]])

- Reduction operations - operations on a matrix. like sum, mean, axis wise sum(dim=0/1), median, max, min, product(prod), std, argmax, argmin

In [ ]:
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 8., 2.],
        [0., 7., 3.]])

# Matrix Operations
- transpose
- dot
- determinate
- inverse

In [2]:
f = torch.randint(size=(2,3), low=0, high=3)
g = torch.randint(size=(3,2), low=0, high=3)

print(f)
print(g)

tensor([[2, 2, 1],
        [2, 1, 2]])
tensor([[1, 1],
        [1, 0],
        [1, 1]])


In [3]:
#matrix multiplication
torch.matmul(f,g)

tensor([[5, 3],
        [5, 4]])

## comparision operation
- greater than
- less than

## Special FUnction

In [3]:
k = torch.tensor([0.001, 20, 30])

In [4]:
torch.log(k) #loge

tensor([-6.9078,  2.9957,  3.4012])

In [5]:
torch.exp(k) #e^x

tensor([1.0010e+00, 4.8517e+08, 1.0686e+13])

In [6]:
torch.sqrt(k)

tensor([0.0316, 4.4721, 5.4772])

In [7]:
torch.sigmoid(k)

tensor([0.5002, 1.0000, 1.0000])

In [8]:
torch.softmax(k, dim=0)

tensor([9.3666e-14, 4.5398e-05, 9.9995e-01])

In [9]:
torch.relu(k)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

In [11]:
import torch.nn.functional as F

# leaky relu
F.leaky_relu(k, negative_slope=0.01)

tensor([1.0000e-03, 2.0000e+01, 3.0000e+01])

# inplace operation
- .add_()
- .relu_()

In [12]:
#memory address in tensor
id(k)

136080513922736

# BackWard Propagation

In [13]:
data = torch.tensor(
    [
        [2,3,3],
        [5,6,4],
        [7,8,5]
    ]
)
data

tensor([[2, 3, 3],
        [5, 6, 4],
        [7, 8, 5]])

In [14]:
X = data[:,0:2].float()
y = data[:,2].float()

# Weight Initialization

In [16]:
#w =1, b =0
def init_params():
  params = {}
  params['W1'] = torch.ones((2,2)) * 0.1
  params['b1'] = torch.zeros((2,1))

  params['W2'] = torch.ones((2,1)) * 0.1
  params['b2'] = torch.zeros((1,1))

  return params

In [17]:
init_params()

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Better way

{'W1': tensor([[0.1000, 0.1000],
         [0.1000, 0.1000]]),
 'b1': tensor([[0.],
         [0.]]),
 'W2': tensor([[0.1000],
         [0.1000]]),
 'b2': tensor([[0.]])}

# Forward Propagation

tensor([[2., 3.],
        [5., 6.],
        [7., 8.]])

tensor([[0.1000]])

tensor([[0.5000],
        [0.5000]])

tensor([[ 8.4100, 15.2100, 24.0100]])

{'W1': tensor([[0.1909, 0.2086],
         [0.1923, 0.2103]]),
 'b1': tensor([[0.0177],
         [0.0180]]),
 'W2': tensor([[0.2541],
         [0.2624]]),
 'b2': tensor([[0.1032]])}

tensor([[0.2541],
        [0.2624]])

tensor(0.2541)

tensor(0.2624)

tensor([[2.6973],
        [2.9377]])

Epoch - 1 Loss - 14.67866039276123
Epoch - 2 Loss - 13.701451301574707
Epoch - 3 Loss - 12.494118690490723
Epoch - 4 Loss - 11.040447076161703
Epoch - 5 Loss - 9.366330782572428
