<a href="https://colab.research.google.com/github/habib-153/AI-ML/blob/Deep-learning/nn_module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import torch.nn as nn

In [7]:
class Model(nn.Module):
  def __init__(self, num_features):
    super().__init__()

    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out


In [4]:
features = torch.rand(10,5)

In [5]:
features

tensor([[0.9879, 0.2566, 0.9418, 0.4858, 0.6611],
        [0.1626, 0.5205, 0.1822, 0.4119, 0.2738],
        [0.0408, 0.9468, 0.2815, 0.8486, 0.2872],
        [0.3284, 0.8552, 0.8368, 0.0285, 0.6616],
        [0.0250, 0.3583, 0.5074, 0.3049, 0.5835],
        [0.1961, 0.8553, 0.7982, 0.6283, 0.9275],
        [0.1939, 0.3726, 0.5128, 0.3519, 0.2280],
        [0.5712, 0.7440, 0.5243, 0.2423, 0.5783],
        [0.9119, 0.4166, 0.2213, 0.0391, 0.0154],
        [0.2099, 0.1699, 0.3557, 0.4209, 0.4927]])

In [8]:
#create model
model = Model(features.shape[1])

In [11]:
#call model forward
model(features)

tensor([[0.6040],
        [0.6079],
        [0.6311],
        [0.7123],
        [0.6309],
        [0.6704],
        [0.6252],
        [0.6536],
        [0.6009],
        [0.5822]], grad_fn=<SigmoidBackward0>)

In [12]:
model.linear.weight

Parameter containing:
tensor([[-0.1734,  0.4323,  0.3664, -0.3275, -0.0343]], requires_grad=True)

In [13]:
#visualize
!pip install torchinfo

In [14]:
from torchinfo import summary
summary(model, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

# Version 2

In [15]:
class Model2(nn.Module):
  def __init__(self, num_features):
    super().__init__()
    #layer 1
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()

    #layer 2
    self.linear2 = nn.Linear(3,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [16]:
features = torch.rand(10,5)

In [17]:
model2 = Model2(features.shape[1])

In [18]:
model2(features)

tensor([[0.5439],
        [0.5215],
        [0.5387],
        [0.5218],
        [0.5393],
        [0.5422],
        [0.5391],
        [0.5306],
        [0.5370],
        [0.5413]], grad_fn=<SigmoidBackward0>)

In [19]:
model2.linear1.weight

Parameter containing:
tensor([[ 0.3283,  0.1093, -0.0080,  0.3705, -0.1901],
        [-0.3672,  0.4164, -0.1028, -0.0116, -0.1707],
        [ 0.3047,  0.1838, -0.2029, -0.0019,  0.3553]], requires_grad=True)

In [20]:
summary(model2, input_size=(10, 5))

Layer (type:depth-idx)                   Output Shape              Param #
Model2                                   [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00